---
#info: Prepare hosts that don't have python3
- hosts: all
  gather_facts: false
  strategy: free
  become: true

  pre_tasks:
    - name: Install python3
      raw: |
        INSTALLED=$(command -v python3)
        if [ -z "${INSTALLED}" ]; then
          if [ -z "$(find -H /var/lib/apt/lists -maxdepth 0 -mtime -1)" ]; then
            echo "Updating apt cache"
            apt-get -qq -y update
          fi
          echo "Installing python3"
          apt-get -qq -y install python3 python3-apt
        fi
      args:
        executable: /bin/sh
      register: shell
      changed_when: "'Installing python3' in shell.stdout"

    - debug:
        var=shell.stdout_lines
      when: shell.stdout